;;;; format.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'format
  'format
  (scheme#list)
  '((read/comments . format#read/comments)
    (tidy . format#tidy)
    (write/comments . format#write/comments)
    (blank-symbol . format#blank-symbol)
    (comment-symbol . format#comment-symbol)
    (widths . format#widths))
  (scheme#list)
  (scheme#list))

;; END OF FILE
